#!/bin/bash

set -e
. /usr/share/debconf/confmodule

case "$1" in
  configure)
    systemctl daemon-reload
    systemctl status emercoind >/dev/null 2>&1 && systemctl restart emercoind || {
      systemctl is-enabled emercoind >/dev/null 2>&1 && systemctl start emercoind
    }
  ;;
esac

exit 0
