#!/bin/bash

set -e
. /usr/share/debconf/confmodule

case "$1" in
  install)
    getent passwd emc >/dev/null || {
      mkdir /tmp/emcskel
      groupadd emc
      useradd -m -d /var/lib/emc -k /tmp/emcskel -s /bin/false -g emc emc
      rmdir /tmp/emcskel
    }
    [ ! -f /etc/ssl/emc/emercoin.key ] || [ ! -f /etc/ssl/emc/emercoin.crt ] && {
      mkdir -p /etc/ssl/emc
      openssl req -nodes -x509 -newkey rsa:4096 -keyout /etc/ssl/emc/emercoin.key -out /etc/ssl/emc/emercoin.crt -days 3560 -subj /C=CY/L=Nicosia/O=Emercoin/CN=emercoin.emc
      chown emc.emc /etc/ssl/emc/emercoin.key /etc/ssl/emc/emercoin.crt
      chmod 600 /etc/ssl/emc/emercoin.key
    }
    touch /var/tmp/emercoin-install.flag
  ;;
esac

[ -f /var/lib/emc/.emercoin/emercoin.conf ] && sed -i -e 's|rpcallowip=\*|rpcallowip=0.0.0.0/0|' /var/lib/emc/.emercoin/emercoin.conf || true
[ -f /var/lib/emc/.emercoin/addr.dat ] && { 
  systemctl status emercoind >/dev/null 2>&1 && systemctl stop emercoind >/dev/null 2>&1 || true
  cd /var/lib/emc/.emercoin && rm -rf database addr.dat nameindex* blk* *.log .lock
} || true

exit 0
