#!/bin/bash

chown -R emc.emc /var/lib/emc/.emercoin /usr/bin/emercoin-cli
chmod u+s /usr/bin/emercoin-cli

getent passwd emc >/dev/null || {
  groupadd -r emc && useradd -r -m -d /var/lib/emc -k /dev/null -s /bin/false -g emc emc
}

mkdir -p /etc/ssl/emc
[ ! -f /etc/ssl/emc/emercoin.key ] || [ ! -f /etc/ssl/emc/emercoin.crt ] && openssl req -nodes -x509 -newkey rsa:4096 -keyout /etc/ssl/emc/emercoin.key -out /etc/ssl/emc/emercoin.crt -days 3560 -subj /C=US/ST=Oregon/L=Portland/O=IT/CN=emercoin.emc

[ -f /var/lib/emc/.emercoin/addr.dat ] && { cd /var/lib/emc/.emercoin && rm -rf database addr.dat nameindex* blk* *.log .lock; }
[ -f /var/lib/emc/.emercoin/emercoin.conf ] && { 
  sed -i -e 's|rpcallowip=\*|rpcallowip=0.0.0.0/0|' /var/lib/emc/.emercoin/emercoin.conf
  service emercoind status >/dev/null && service emercoind restart >/dev/null
  exit 0
}

mkdir -p /etc/logrotate.d
cat<<EOF > /etc/logrotate.d/emercoind
/var/lib/emc/.emercoin/*.log
{
  weekly
  rotate 6
  compress
  delaycompress
  missingok
  create 0644 emc emc
}
EOF

mkdir -p /var/lib/emc/.emercoin
cat<<EOF >/var/lib/emc/.emercoin/emercoin.conf
rpcuser=emccoinrpc
rpcpassword=`$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)`
listen=1
server=1
rpcallowip=127.0.0.1
rpcport=6662
maxconnections=80
gen=0
daemon=1
rpcssl=1
rpcsslcertificatechainfile=/etc/ssl/emc/emercoin.crt
rpcsslprivatekeyfile=/etc/ssl/emc/emercoin.key
rpcsslciphers=HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:!SSLv2
EOF

chmod 600 /var/lib/emc/.emercoin/emercoin.conf
mkdir -p /etc/emercoin
ln -s /var/lib/emc/.emercoin/emercoin.conf /etc/emercoin/emercoin.conf
ln -s /etc/ssl/emc /etc/emercoin/certs

update-rc.d emercoind defaults
service emercoind start

exit 0
